# Generated by Django 6.0.3 on 2026-04-06 13:50

from django.db import migrations


def create_prompts(apps, schema_editor):
    Prompt = apps.get_model('chat', 'Prompt')
    prompts = [
        {
            'lang': 'it',
            'content': "Sei {name}. Rispondi come il personaggio, in prima persona, "
                       "nella lingua '{lang}', basandoti su ciò che è pubblicamente "
                       "noto sulla tua vita, sul tuo lavoro e sulla tua epoca. "
                       "{description} {biography}\n\nContext:\n{context}"
        },
        {
            'lang': 'fr',
            'content': "Vous êtes {name}. Répondez en tant que personnage, à la première personne, "
                       "dans la langue '{lang}', en vous appuyant sur ce qui est publiquement "
                       "connu de votre vie, de votre travail et de votre époque. "
                       "{description} {biography}\n\nContext:\n{context}"
        },
        {
            'lang': 'de',
            'content': "Sie sind {name}. Antworten Sie in Ihrer Rolle als Person, in der ersten Person, "
                       "in der Sprache '{lang}', basierend auf dem, was öffentlich über Ihr Leben, "
                       "Ihre Arbeit und Ihre Ära bekannt ist. "
                       "{description} {biography}\n\nContext:\n{context}"
        },
        {
            'lang': 'en',
            'content': "You are {name}. Respond in character, in first person, "
                       "in language '{lang}', drawing on what is publicly known about your life, "
                       "work, and era. {description} {biography}\n\nContext:\n{context}"
        },
    ]
    for prompt_data in prompts:
        obj, created = Prompt.objects.get_or_create(lang=prompt_data['lang'], defaults={'content': prompt_data['content']})
        if not created and '{context}' not in obj.content:
            obj.content = prompt_data['content']
            obj.save()

def remove_prompts(apps, schema_editor):
    Prompt = apps.get_model('chat', 'Prompt')
    Prompt.objects.filter(lang__in=['it', 'fr', 'de', 'en']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_prompt'),
    ]

    operations = [
        migrations.RunPython(create_prompts, remove_prompts),
    ]
