# Generated by Django 6.0.3 on 2026-04-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_seed_prompts'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='lang',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
