# Generated by Django 6.0.3 on 2026-04-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Legend',
            fields=[
                ('slug', models.SlugField(max_length=120, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
