# Generated by Django 6.0.3 on 2026-04-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legends', '0002_seed_legends'),
    ]

    operations = [
        migrations.AddField(
            model_name='legend',
            name='biography',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='legend',
            name='lang',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
